/* eslint-disable quotes */
import VOE01 from "./assets/images/01.png";
import VOE02 from "./assets/images/02.png";
import VOE03 from "./assets/images/03.png";
import VOE04 from "./assets/images/04.png";
import VOE05 from "./assets/images/05.png";
import VOE06 from "./assets/images/06.png";
import VOE07 from "./assets/images/07.png";
import VOE08 from "./assets/images/08.png";
import VOE09 from "./assets/images/09.png";
import VOE10 from "./assets/images/10.png";
import VOE11 from "./assets/images/11.png";
import VOE12 from "./assets/images/12.png";
import VOE13 from "./assets/images/13.png";

export default [
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE01,
    title: 'Elo de Esteira Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE02,
    title: 'Pinos e Buchas Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE03,
    title: 'Correntes Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE04,
    title: 'Aro Motriz Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE05,
    title: 'Rolete Superior Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE06,
    title: 'Rolete Inferior Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE07,
    title: 'Roda Guia Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE08,
    title: 'Mola Tensora Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE09,
    title: 'Sapata Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE10,
    title: 'Proteção de Esteira Volvo',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE11,
    title: 'Dentes para Escavadeira',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE12,
    title: 'Adaptador p/ Escavadeira',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
  {
    ref: '9020549383',
    volume: false,
    imgData: VOE13,
    title: 'Dentes para Pá Carregadeira',
    description: '5% de DESCONTO',
    oldPrice: '800,42',
    newPrice: 499.99,
    qtd: 0,
    destaque: false,
    obs: false,
  },
];
